# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
# env = UnityEnvironment(file_name='/home/arasdar/unity-envs/Reacher_Linux/Reacher.x86_64')
# env = UnityEnvironment(file_name='/home/arasdar/unity-envs/Reacher_Linux_v1/Reacher.x86_64')
env = UnityEnvironment(file_name='/home/arasdar/unity-envs/Reacher_Linux_OneAgent/Reacher_Linux/Reacher.x86_64')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_size -> 5.0
		goal_speed -> 1.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 1
Size of each action: 4
There are 1 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726671e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [5]:
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

Total score (averaged over agents) this episode: 0.36999999172985554


When finished, you can close the environment.

In [6]:
# env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [25]:
# Testing the train mode
env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
state = env_info.vector_observations[0]                  # get the current state (for each agent)
#scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    action = np.random.randn(num_agents, action_size) # select an action (for each agent)
    print(action)
    action = np.clip(action, -1, 1)                  # all actions between -1 and 1
    print(action)
    env_info = env.step(action)[brain_name]           # send all actions to tne environment
    next_state = env_info.vector_observations[0]         # get next state (for each agent)
    reward = env_info.rewards[0]                         # get reward (for each agent)
    done = env_info.local_done[0]                        # see if episode finished
    #scores += env_info.rewards                         # update the score (for each agent)
    state = next_state                               # roll over states to next time step
    if done is True:                                  # exit loop if episode finished
        print(action.shape, reward)
        print(done)
        break
# print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

[[ 0.04132238  1.16787986 -1.20311761 -0.63333404]]
[[ 0.04132238  1.         -1.         -0.63333404]]
[[-2.02509557 -0.52146821 -0.3034164  -0.91576877]]
[[-1.         -0.52146821 -0.3034164  -0.91576877]]
[[ 0.99315489 -0.15724581  0.58884435 -0.3994452 ]]
[[ 0.99315489 -0.15724581  0.58884435 -0.3994452 ]]
[[ 0.38535277  0.60623296 -0.25889972  2.24101009]]
[[ 0.38535277  0.60623296 -0.25889972  1.        ]]
[[0.76417825 1.24933054 1.00072726 0.84404804]]
[[0.76417825 1.         1.         0.84404804]]
[[ 0.7254801  -0.83156043 -0.50669729 -0.52762241]]
[[ 0.7254801  -0.83156043 -0.50669729 -0.52762241]]
[[0.65084496 0.68955476 0.88496306 0.5549794 ]]
[[0.65084496 0.68955476 0.88496306 0.5549794 ]]
[[ 1.74617631 -0.48815454 -0.02694049  0.23416623]]
[[ 1.         -0.48815454 -0.02694049  0.23416623]]
[[-0.71176381  0.21984852  0.53702353 -1.17661051]]
[[-0.71176381  0.21984852  0.53702353 -1.        ]]
[[-0.56538959 -0.09103713 -2.03983121 -0.24821297]]
[[-0.56538959 -0.09103713 -1

[[-0.23483207  1.23839372  1.51660133 -0.69592067]]
[[-0.23483207  1.          1.         -0.69592067]]
[[-2.16836468  1.68049021 -0.03072991  0.11099958]]
[[-1.          1.         -0.03072991  0.11099958]]
[[-1.22580511  0.39629915 -2.06523961 -0.03281379]]
[[-1.          0.39629915 -1.         -0.03281379]]
[[ 0.04190639 -0.89933463 -0.87111579  2.53825508]]
[[ 0.04190639 -0.89933463 -0.87111579  1.        ]]
[[ 1.27077061  0.27133024 -0.87794319  0.27618172]]
[[ 1.          0.27133024 -0.87794319  0.27618172]]
[[ 0.38879375  0.68206661  1.15335446 -0.52263313]]
[[ 0.38879375  0.68206661  1.         -0.52263313]]
[[ 0.42374583  0.83591605 -0.561845    0.32673945]]
[[ 0.42374583  0.83591605 -0.561845    0.32673945]]
[[ 0.28789565 -0.75954056 -1.37785794 -0.07148687]]
[[ 0.28789565 -0.75954056 -1.         -0.07148687]]
[[ 0.10709144  1.11060256 -0.072866   -0.2604893 ]]
[[ 0.10709144  1.         -0.072866   -0.2604893 ]]
[[-1.65781908 -0.41911428  1.61499236 -0.21593206]]
[[-1.       

[[ 0.60506964 -1.24590712  0.22450819  1.60372905]]
[[ 0.60506964 -1.          0.22450819  1.        ]]
[[ 0.23275889 -1.38865002 -0.48811103  0.85085111]]
[[ 0.23275889 -1.         -0.48811103  0.85085111]]
[[-0.97192096 -0.72004463 -0.86099377  0.74012587]]
[[-0.97192096 -0.72004463 -0.86099377  0.74012587]]
[[ 0.42852596  1.28206469 -0.44227654  1.53326972]]
[[ 0.42852596  1.         -0.44227654  1.        ]]
[[ 1.89603381 -2.05038877  1.14777807 -1.43786575]]
[[ 1. -1.  1. -1.]]
[[ 0.56015742  0.37596689 -0.49921155 -0.1601116 ]]
[[ 0.56015742  0.37596689 -0.49921155 -0.1601116 ]]
[[ 1.32932372  1.1017954  -0.3274329  -0.34576315]]
[[ 1.          1.         -0.3274329  -0.34576315]]
[[ 0.33863823  1.06963429  0.00540916 -0.21287536]]
[[ 0.33863823  1.          0.00540916 -0.21287536]]
[[-0.59710954  1.99136538 -1.4122192  -1.16202612]]
[[-0.59710954  1.         -1.         -1.        ]]
[[-0.37538724 -0.1491982  -0.27962474  0.69646404]]
[[-0.37538724 -0.1491982  -0.27962474  0.696

[[ 0.43834282 -0.81389495 -0.51741438 -0.75744485]]
[[ 0.43834282 -0.81389495 -0.51741438 -0.75744485]]
[[-0.76716083  1.57033144  1.50193018 -1.11946702]]
[[-0.76716083  1.          1.         -1.        ]]
[[-0.67197442 -1.37741444  1.18605724 -0.72707074]]
[[-0.67197442 -1.          1.         -0.72707074]]
[[-0.05044931 -0.94202394 -1.50719212 -1.06127311]]
[[-0.05044931 -0.94202394 -1.         -1.        ]]
[[1.53121915 1.15844413 0.52807938 1.25620366]]
[[1.         1.         0.52807938 1.        ]]
[[ 1.16027208  1.02979668 -0.2992426  -1.44014594]]
[[ 1.         1.        -0.2992426 -1.       ]]
[[ 1.73808568 -0.46299986 -0.38353373 -0.08680405]]
[[ 1.         -0.46299986 -0.38353373 -0.08680405]]
[[-2.08729818 -1.49128068  0.95351968  0.44594694]]
[[-1.         -1.          0.95351968  0.44594694]]
[[-1.03835841  2.08246306  0.00386609  1.91305237]]
[[-1.          1.          0.00386609  1.        ]]
[[ 0.56450204 -1.38861172 -0.712416    1.81874409]]
[[ 0.56450204 -1.       

[[-1.03489848 -0.81213267 -0.36475138  0.44820884]]
[[-1.         -0.81213267 -0.36475138  0.44820884]]
[[ 0.30308546 -0.17503726 -1.70809149 -0.04713852]]
[[ 0.30308546 -0.17503726 -1.         -0.04713852]]
[[ 0.73857728  2.19280887 -0.18730437  0.35861875]]
[[ 0.73857728  1.         -0.18730437  0.35861875]]
[[-0.32515408  0.12573272 -0.17996307  0.45638453]]
[[-0.32515408  0.12573272 -0.17996307  0.45638453]]
[[-0.50042727  0.08329452  0.34584279  0.32674824]]
[[-0.50042727  0.08329452  0.34584279  0.32674824]]
[[-0.30402024 -0.12083273 -0.16571465 -0.64064907]]
[[-0.30402024 -0.12083273 -0.16571465 -0.64064907]]
[[ 1.02416974 -1.38917337 -0.14173842 -0.88849624]]
[[ 1.         -1.         -0.14173842 -0.88849624]]
[[-0.86383954  1.37726478 -0.11091372 -0.13661049]]
[[-0.86383954  1.         -0.11091372 -0.13661049]]
[[-1.26486685 -0.0178605   0.47633573 -0.49951375]]
[[-1.         -0.0178605   0.47633573 -0.49951375]]
[[0.43976113 1.46911262 0.35722848 0.09767178]]
[[0.43976113 1. 

[[ 1.62681397  0.28606903 -0.6564331  -0.0729708 ]]
[[ 1.          0.28606903 -0.6564331  -0.0729708 ]]
[[ 0.60743094  1.96759339 -0.29756985  1.55843326]]
[[ 0.60743094  1.         -0.29756985  1.        ]]
[[-0.71121193  0.37556101 -0.35075853 -0.46994056]]
[[-0.71121193  0.37556101 -0.35075853 -0.46994056]]
[[ 0.81508418 -0.99222234  0.7082377   1.42279862]]
[[ 0.81508418 -0.99222234  0.7082377   1.        ]]
[[ 0.31383639 -1.36218202  0.27166599  0.16019977]]
[[ 0.31383639 -1.          0.27166599  0.16019977]]
[[ 0.00624966  0.20492951 -0.73239404  0.99298926]]
[[ 0.00624966  0.20492951 -0.73239404  0.99298926]]
[[-0.08010309 -1.17982739 -0.10881623  1.97747844]]
[[-0.08010309 -1.         -0.10881623  1.        ]]
[[ 0.52397326 -0.07563867 -1.01476268 -0.45377419]]
[[ 0.52397326 -0.07563867 -1.         -0.45377419]]
[[ 0.47687006 -1.57462834  0.40025892  2.19882925]]
[[ 0.47687006 -1.          0.40025892  1.        ]]
[[-2.24782625 -2.81396637 -0.63700983  0.3457925 ]]
[[-1.       

[[ 0.48741851  0.3243896  -1.25863318 -0.88379874]]
[[ 0.48741851  0.3243896  -1.         -0.88379874]]
[[ 0.90382547  0.86322203 -1.15384678  1.41653395]]
[[ 0.90382547  0.86322203 -1.          1.        ]]
[[-0.30608906  2.15443403 -0.3382807  -0.04660943]]
[[-0.30608906  1.         -0.3382807  -0.04660943]]
[[ 0.70986358 -0.29913467  1.9127839  -0.71812877]]
[[ 0.70986358 -0.29913467  1.         -0.71812877]]
[[ 0.11420874 -0.48656561 -1.22618714 -0.29770817]]
[[ 0.11420874 -0.48656561 -1.         -0.29770817]]
[[ 0.46164998  0.0939113  -0.36151817  1.43069597]]
[[ 0.46164998  0.0939113  -0.36151817  1.        ]]
[[ 0.01400857  0.13328467 -1.71504205 -0.68089064]]
[[ 0.01400857  0.13328467 -1.         -0.68089064]]
[[ 0.6564507  -0.01364613  1.02980222 -2.13084919]]
[[ 0.6564507  -0.01364613  1.         -1.        ]]
[[ 1.16915108 -0.35089846  0.06466845  1.18747508]]
[[ 1.         -0.35089846  0.06466845  1.        ]]
[[-0.66922374 -2.52069159 -1.68284819  1.01522684]]
[[-0.6692237

[[-0.4778979   0.25305442  1.40203414  0.13432149]]
[[-0.4778979   0.25305442  1.          0.13432149]]
[[ 0.19900003 -1.38162465 -0.06662986  0.33491365]]
[[ 0.19900003 -1.         -0.06662986  0.33491365]]
[[-1.36154319 -0.76865792 -0.39449067  0.57332982]]
[[-1.         -0.76865792 -0.39449067  0.57332982]]
[[-0.17361445  0.37850212  0.31443176 -1.14236933]]
[[-0.17361445  0.37850212  0.31443176 -1.        ]]
[[ 0.14221618 -1.48285288  0.16258733  0.38769049]]
[[ 0.14221618 -1.          0.16258733  0.38769049]]
[[0.63273991 0.37618437 1.32291193 0.31138464]]
[[0.63273991 0.37618437 1.         0.31138464]]
[[-1.03252783 -1.45353416  0.79200779 -1.39412792]]
[[-1.         -1.          0.79200779 -1.        ]]
[[ 0.25485778 -0.56320347 -0.04567319  0.45400089]]
[[ 0.25485778 -0.56320347 -0.04567319  0.45400089]]
[[-0.20909033  0.0581421  -1.17631325  0.48121473]]
[[-0.20909033  0.0581421  -1.          0.48121473]]
[[ 0.89378954 -2.95232473 -0.43319645  0.36099869]]
[[ 0.89378954 -1.   

[[-0.46348107 -0.86065202  0.2979715  -0.86364386]]
[[-0.46348107 -0.86065202  0.2979715  -0.86364386]]
[[ 0.60481633 -0.65378047  1.39161713  0.10900263]]
[[ 0.60481633 -0.65378047  1.          0.10900263]]
[[1.16444153 0.36278918 0.12315544 0.09402783]]
[[1.         0.36278918 0.12315544 0.09402783]]
[[-0.10220102 -0.70070948  0.58404013 -0.20590323]]
[[-0.10220102 -0.70070948  0.58404013 -0.20590323]]
[[-0.82308247  1.47057755 -0.54241783 -0.05688968]]
[[-0.82308247  1.         -0.54241783 -0.05688968]]
[[-0.44683772 -0.86142854  0.315585    0.08610039]]
[[-0.44683772 -0.86142854  0.315585    0.08610039]]
[[ 0.92706021  1.22111773  0.6303385  -1.53553279]]
[[ 0.92706021  1.          0.6303385  -1.        ]]
[[ 0.79276381 -0.34727295 -0.83224095 -0.12301246]]
[[ 0.79276381 -0.34727295 -0.83224095 -0.12301246]]
[[-0.56367899 -1.45959951 -0.19835753  0.27724308]]
[[-0.56367899 -1.         -0.19835753  0.27724308]]
[[ 0.53885021  0.69084897 -1.26133691  0.35467103]]
[[ 0.53885021  0.690

[[ 1.35646225  0.87926471 -1.10560155 -0.79540124]]
[[ 1.          0.87926471 -1.         -0.79540124]]
[[ 0.05682806 -0.23053607  0.85778675 -1.07102261]]
[[ 0.05682806 -0.23053607  0.85778675 -1.        ]]
[[-1.15996702  1.18888623  1.54387098 -0.34628771]]
[[-1.          1.          1.         -0.34628771]]
[[-0.29062434 -1.39118147  1.03652958  1.13701022]]
[[-0.29062434 -1.          1.          1.        ]]
[[ 0.85624469 -0.47943327 -1.37973678  0.03005942]]
[[ 0.85624469 -0.47943327 -1.          0.03005942]]
[[ 0.40558128 -0.05381839 -1.29124082 -0.9465901 ]]
[[ 0.40558128 -0.05381839 -1.         -0.9465901 ]]
[[-1.05207164 -0.53601504 -0.14177467 -0.86873174]]
[[-1.         -0.53601504 -0.14177467 -0.86873174]]
[[-1.05715245 -0.96678067  1.86887053  1.09167388]]
[[-1.         -0.96678067  1.          1.        ]]
[[ 0.12100099 -0.76487987 -0.20573417  0.98408924]]
[[ 0.12100099 -0.76487987 -0.20573417  0.98408924]]
[[-0.70790428  0.28776484 -0.0034798   1.31126508]]
[[-0.7079042

## Option 1: Solve the First Version
The task is episodic, and in order to solve the environment, your agent must get an average score of +30 over 100 consecutive episodes.

In [26]:
# In this one we should define and detect GPUs for tensorflow
# GPUs or CPU
import tensorflow as tf

# Check TensorFlow Version
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 1.7.1
Default GPU Device: 


In [27]:
def model_input(state_size, action_size):
    #states = tf.placeholder(tf.float32, [None, *state_size], name='states')
    states = tf.placeholder(tf.float32, [None, state_size], name='states')
    actions = tf.placeholder(tf.float32, [None, action_size], name='actions')
    targetQs = tf.placeholder(tf.float32, [None], name='targetQs')
    return states, actions, targetQs

In [28]:
# Generator/Controller: Generating/prediting the actions
def generator(states, action_size, hidden_size, reuse=False, alpha=0.1, training=False):
    with tf.variable_scope('generator', reuse=reuse):
        # First fully connected layer
        h1 = tf.layers.dense(inputs=states, units=hidden_size)
        bn1 = tf.layers.batch_normalization(h1, training=training)        
        nl1 = tf.maximum(alpha * bn1, bn1)
        
        # Second fully connected layer
        h2 = tf.layers.dense(inputs=nl1, units=hidden_size)
        bn2 = tf.layers.batch_normalization(h2, training=training)        
        nl2 = tf.maximum(alpha * bn2, bn2)
        
        # Output layer
        logits = tf.layers.dense(inputs=nl2, units=action_size)        
        #predictions = tf.nn.softmax(logits)

        # return actions logits
        return logits

In [29]:
# Discriminator/Dopamine: Reward function/planner/naviator/advisor/supervisor/cortical columns
def discriminator(states, actions, hidden_size, reuse=False, alpha=0.1, training=False):
    with tf.variable_scope('discriminator', reuse=reuse):
        # Fusion/merge states and actions/ SA/ SM
        x_fused = tf.concat(axis=1, values=[states, actions])
        
        # First fully connected layer
        h1 = tf.layers.dense(inputs=x_fused, units=hidden_size)
        bn1 = tf.layers.batch_normalization(h1, training=training)        
        nl1 = tf.maximum(alpha * bn1, bn1)
        
        # Second fully connected layer
        h2 = tf.layers.dense(inputs=nl1, units=hidden_size)
        bn2 = tf.layers.batch_normalization(h2, training=training)        
        nl2 = tf.maximum(alpha * bn2, bn2)
        
        # Output layer
        logits = tf.layers.dense(inputs=nl2, units=1)        
        #predictions = tf.nn.softmax(logits)

        # return rewards logits
        return logits

In [47]:
def model_loss(action_size, hidden_size, states, targetQs, # Used
               actions): # NOT used
    actions_logits = generator(states=states, hidden_size=hidden_size, action_size=action_size)
    Qs = discriminator(actions=actions_logits, hidden_size=hidden_size, states=states)
    g_loss = tf.reduce_mean(Qs)
    d_loss = tf.reduce_mean(tf.square(Qs - targetQs))
    g_loss1 = tf.abs(tf.reduce_mean(Qs))
    g_loss2 = tf.reduce_mean(targetQs)
    return actions_logits, Qs, g_loss, d_loss, g_loss1, g_loss2

In [48]:
# def model_loss(action_size, hidden_size, states, actions, targetQs):
#     actions_logits = generator(states=states, hidden_size=hidden_size, action_size=action_size)
#     neg_log_prob_actions = tf.nn.sigmoid_cross_entropy_with_logits(logits=actions_logits, 
#                                                                    labels=tf.nn.sigmoid(actions))
#     gQs = discriminator(actions=actions_logits, hidden_size=hidden_size, states=states)
#     dQs = discriminator(actions=actions, hidden_size=hidden_size, states=states, reuse=True)
#     g_loss = tf.reduce_mean(neg_log_prob_actions * dQs)
#     g_loss1 = tf.reduce_mean(neg_log_prob_actions)
#     g_loss2 = tf.reduce_mean(dQs)
#     d_loss = tf.reduce_mean(tf.square(dQs - targetQs))
#     return actions_logits, gQs, g_loss, d_loss, g_loss1, g_loss2

In [49]:
# Optimizating/training/learning G & D
def model_opt(g_loss, d_loss, learning_rate):
    # Get weights and bias to update
    t_vars = tf.trainable_variables()
    g_vars = [var for var in t_vars if var.name.startswith('generator')]
    d_vars = [var for var in t_vars if var.name.startswith('discriminator')]

    # Optimize
    with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)): # Required for batchnorm (BN)
        g_opt = tf.train.AdamOptimizer(learning_rate).minimize(g_loss, var_list=g_vars)
        d_opt = tf.train.AdamOptimizer(learning_rate).minimize(d_loss, var_list=d_vars)

    return g_opt, d_opt

In [50]:
class Model:
    def __init__(self, state_size, action_size, hidden_size, learning_rate):

        # Data of the Model: make the data available inside the framework
        self.states, self.actions, self.targetQs = model_input(state_size=state_size, action_size=action_size)

        # Create the Model: calculating the loss and forwad pass
        self.actions_logits, self.Qs_logits, self.g_loss, self.d_loss, self.g_loss1, self.g_loss2 = model_loss(
            action_size=action_size, hidden_size=hidden_size, # model init parameters
            states=self.states, actions=self.actions, targetQs=self.targetQs) # model input
        
        # Update the model: backward pass and backprop
        self.g_opt, self.d_opt = model_opt(g_loss=self.g_loss, d_loss=self.d_loss, learning_rate=learning_rate)

In [51]:
from collections import deque
class Memory():
    def __init__(self, max_size = 1000):
        self.buffer = deque(maxlen=max_size)
    def sample(self, batch_size):
        idx = np.random.choice(np.arange(len(self.buffer)), 
                               size=batch_size, 
                               replace=False)
        return [self.buffer[ii] for ii in idx]

In [52]:
print('state size:{}'.format(states.shape), 
      'actions:{}'.format(actions.shape)) 
print('action size:{}'.format(np.max(actions) - np.min(actions)+1))

state size:(1, 33) actions:(1, 4)
action size:2.1437777898923063


In [53]:
# Exploration parameters
explore_start = 1.0            # exploration probability at start
explore_stop = 0.01            # minimum exploration probability 
decay_rate = 0.0001            # exponential decay rate for exploration prob

# Network parameters
state_size = 33
action_size = 4
hidden_size = 33*2             # number of units in each Q-network hidden layer
learning_rate = 0.0001         # Q-network learning rate

# Memory parameters
memory_size = 10000            # memory capacity
batch_size = 100               # experience mini-batch size
gamma = 0.99                   # future reward discount

In [54]:
# Reset/init the graph/session
graph = tf.reset_default_graph()

# Init the model
model = Model(action_size=action_size, state_size=state_size, hidden_size=hidden_size, learning_rate=learning_rate)

# Init the memory
memory = Memory(max_size=memory_size)

In [55]:
# Initializing the memory buffer
env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
state = env_info.vector_observations[0]                  # get the current state (for each agent)
for _ in range(memory_size):
    action = np.random.randn(num_agents, action_size) # select an action (for each agent)
    #action = np.clip(action, -1, 1)                  # all actions between -1 and 1
    env_info = env.step(action)[brain_name]           # send all actions to tne environment
    next_state = env_info.vector_observations[0]         # get next state (for each agent)
    reward = env_info.rewards[0]                         # get reward (for each agent)
    done = env_info.local_done[0]                        # see if episode finished
    memory.buffer.append([state, action.reshape([-1]), next_state, reward, float(done)])
    #print(state.shape, action.reshape([-1]).shape, reward, float(done))
    state = next_state                               # roll over states to next time step
    if done is True:                                  # exit loop if episode finished
        print(done)
        env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
        state = env_info.vector_observations[0]                  # get the current state (for each agent)
        break

True


In [56]:
# len(memory.buffer), memory.buffer[100]

In [ ]:
# Save/load the model and save for plotting
saver = tf.train.Saver()
episode_rewards_list, rewards_list, gloss_list, dloss_list = [], [], [], []

# TF session for training
with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    #saver.restore(sess, 'checkpoints/model.ckpt')    
    #saver.restore(sess, tf.train.latest_checkpoint('checkpoints'))
    total_step = 0 # Explore or exploit parameter
    episode_reward = deque(maxlen=100) # 100 episodes average/running average/running mean/window
    
    # Training episodes/epochs
    for ep in range(111):
        total_reward = 0
        gloss_batch, dloss_batch = [], []
        gloss1_batch, gloss2_batch = [], []
        #state = env.reset()
        env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
        state = env_info.vector_observations[0]                  # get the current state (for each agent)

        # Training steps/batches
        while True:
            # Explore (Env) or Exploit (Model): NO
            total_step += 1
            explore_p = explore_stop + (explore_start - explore_stop) * np.exp(-decay_rate * total_step) 
            # if explore_p > np.random.rand():
            #     #action = env.action_space.sample()
            #     action = np.random.randn(num_agents, action_size) # select an action (for each agent)
            # else:
            action = sess.run(model.actions_logits, feed_dict={model.states: state.reshape([1, -1])})
            #print(action.shape)
            #action = np.reshape(action_logits, [-1]) # For continuous action space
            #action = np.argmax(action_logits) # For discrete action space
            #next_state, reward, done, _ = env.step(action)
            env_info = env.step(action)[brain_name]           # send all actions to tne environment
            next_state = env_info.vector_observations[0]         # get next state (for each agent)
            reward = env_info.rewards[0]                         # get reward (for each agent)
            done = env_info.local_done[0]                        # see if episode finished
            memory.buffer.append([state, action.reshape([-1]), next_state, reward, float(done)])
            total_reward += reward
            state = next_state

            # Training
            batch = memory.sample(batch_size)
            #batch = memory.buffer
            states = np.array([each[0] for each in batch])
            actions = np.array([each[1] for each in batch])
            #print(actions.shape, actions.dtype)
            next_states = np.array([each[2] for each in batch])
            rewards = np.array([each[3] for each in batch])
            dones = np.array([each[4] for each in batch])
            nextQs_logits = sess.run(model.Qs_logits, feed_dict = {model.states: next_states})
            #nextQs = np.max(nextQs_logits, axis=1) * (1-dones)
            nextQs = nextQs_logits.reshape([-1]) * (1-dones)
            targetQs = rewards + (gamma * nextQs)
            #print(nextQs_logits.shape, targetQs.shape)
            gloss, dloss, gloss1, gloss2, _, _ = sess.run([model.g_loss, model.d_loss, 
                                                           model.g_loss1, model.g_loss2,
                                                           model.g_opt, model.d_opt],
                                                          feed_dict = {model.states: states, 
                                                                       model.actions: actions,
                                                                       model.targetQs: targetQs})
            gloss_batch.append(gloss)
            dloss_batch.append(dloss)
            gloss1_batch.append(gloss1)
            gloss2_batch.append(gloss2)
            if done is True:
                break
                
        episode_reward.append(total_reward)
        print('Episode:{}'.format(ep),
              'meanR:{:.4f}'.format(np.mean(episode_reward)),
              'R:{:.4f}'.format(total_reward),
              'gloss:{:.4f}'.format(np.mean(gloss_batch)),
              'dloss:{:.4f}'.format(np.mean(dloss_batch)),
                # g_loss1 = tf.reduce_mean(neg_log_prob_actions)
                # g_loss2 = tf.reduce_mean(Qs)
              'gloss1:{:.4f}'.format(np.mean(gloss1_batch)),
              'gloss2:{:.4f}'.format(np.mean(gloss2_batch)),
              'exploreP:{:.4f}'.format(explore_p))
        # Ploting out
        episode_rewards_list.append([ep, np.mean(episode_reward)])
        rewards_list.append([ep, total_reward])
        gloss_list.append([ep, np.mean(gloss_batch)])
        dloss_list.append([ep, np.mean(dloss_batch)])
        # Break episode/epoch loop
        ## Option 1: Solve the First Version
        #The task is episodic, and in order to solve the environment, 
        #your agent must get an average score of +30 over 100 consecutive episodes.        
        if np.mean(episode_reward) >= +30:
            break
            
    # At the end of all training episodes/epochs
    saver.save(sess, 'checkpoints/model.ckpt')

Episode:0 meanR:0.6700 R:0.6700 gloss:-0.0165 dloss:0.1412 gloss1:0.1288 gloss2:-0.0164 exploreP:0.9057
Episode:1 meanR:0.4700 R:0.2700 gloss:0.0645 dloss:0.0112 gloss1:0.0718 gloss2:0.0641 exploreP:0.8204
Episode:2 meanR:0.6467 R:1.0000 gloss:0.0250 dloss:0.0073 gloss1:0.0408 gloss2:0.0251 exploreP:0.7432
Episode:3 meanR:0.5675 R:0.3300 gloss:0.0452 dloss:0.0065 gloss1:0.0490 gloss2:0.0453 exploreP:0.6734
Episode:4 meanR:0.4540 R:0.0000 gloss:0.0358 dloss:0.0038 gloss1:0.0430 gloss2:0.0359 exploreP:0.6102
Episode:5 meanR:0.3783 R:0.0000 gloss:0.0381 dloss:0.0021 gloss1:0.0420 gloss2:0.0381 exploreP:0.5530
Episode:6 meanR:0.3243 R:0.0000 gloss:0.0063 dloss:0.0022 gloss1:0.0298 gloss2:0.0064 exploreP:0.5013
Episode:7 meanR:0.2837 R:0.0000 gloss:0.0129 dloss:0.0016 gloss1:0.0272 gloss2:0.0129 exploreP:0.4545
Episode:8 meanR:0.2522 R:0.0000 gloss:0.0161 dloss:0.0008 gloss1:0.0247 gloss2:0.0161 exploreP:0.4121
Episode:9 meanR:0.2270 R:0.0000 gloss:0.0228 dloss:0.0007 gloss1:0.0289 gloss2:0