# Continuous Control

---

You are welcome to use this coding environment to train your agent for the project.  Follow the instructions below to get started!

### 1. Start the Environment

In [1]:
import gym
import random
import torch
import numpy as np
from collections import deque
import matplotlib.pyplot as plt
%matplotlib inline

Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [2]:
env = gym.make('BipedalWalker-v2')

random_seed = 10
env.seed(random_seed)

# from agent import Agent
# agent = Agent(state_size=env.observation_space.shape[0], action_size=env.action_space.shape[0], 
#               random_seed=random_seed)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


/home/arasdar/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


[10]

### 2. Examine the State and Action Spaces

Run the code cell below to print some information about the environment.

In [3]:
env.action_space, env.observation_space

(Box(4,), Box(24,))

In [4]:
action_size = env.action_space.shape[0]
state_size = env.observation_space.shape[0]

In [5]:
action_size, state_size

(4, 24)

In [6]:
env.observation_space.low, env.observation_space.high

(array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf], dtype=float32),
 array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       dtype=float32))

In [7]:
env.action_space.low, env.action_space.high

(array([-1., -1., -1., -1.], dtype=float32),
 array([1., 1., 1., 1.], dtype=float32))

### 3. Instantiate DDPG Agent

In [8]:
from agent2 import Agent

agent = Agent(s_size=state_size, a_size=action_size, random_seed=random_seed)

### 4. Train the Agent with DDPG

In [9]:
from collections import deque
import numpy as np
import time
import torch

n_episodes=3000

n_steps=10000
n_learn=10
learn_every=20

R_goal=-100 # TOCHECK
Rs_deque = deque(maxlen=100)
meanRs = [] # plot

dlosses, glosses, dlosses_Q, dlosses_S = [], [], [], []

In [ ]:
for i_episode in range(n_episodes):
    
    # # Reset Env
    # env_info = env.reset(train_mode=train_mode)[brain_name]       # reset the environment    
    # S = env_info.vector_observations                   # get the current state (for each agent)
    s = env.reset() # s: state
    #print(s.shape)

    #Rs = np.zeros(num_agents)                            # initialize the score (for each agent)
    R = 0 # R: total reward
    dlosses_, glosses_, dlosses_Q_, dlosses_S_ = [], [], [], []
    
    for i_step in range(n_steps):
    #while True:
        
        a = agent.act(np.reshape(s, [1, -1])) # a=[-1, 1]
        #a *= 2
        #print(a.shape)
        
        # Exploration noise
        # noise = np.random.normal(loc=0, scale=0.1, size=[num_agents, action_size])
        # A += noise
        # A = np.clip(a=A, a_min=-1, a_max=1)

        # env_info = env.step(A)[brain_name]            # send all actions to the environment
        # S2 = env_info.vector_observations          # get next state (for each agent)
        # rewards = env_info.rewards                          # get reward (for each agent)
        # dones = env_info.local_done                         # see if episode finished
        #s2: next_state, r: reward, done/terminal, env: environment
        s2, r, done, _ = env.step(np.reshape(a, [-1]))
        #print(s2.shape, r, done)


        # for s, a, reward, s2, done in zip(S, A, rewards, S2, dones):
        # agent.step(state, action, reward, next_state, done) # send actions to the agent
        agent.step(s, a, r, s2, done)

        R += r                           # update the score (for each agent)
        s = s2                                # roll over states to next time step

        dlosses__, glosses__, dlosses_Q__, dlosses_S__ = [], [], [], []
        if i_step%learn_every == 0:
            for _ in range(n_learn):
                dloss, gloss, dloss_Q, dloss_S = agent.start_learn()
                dlosses__.append(dloss)
                glosses__.append(gloss)
                dlosses_Q__.append(dloss_Q)
                dlosses_S__.append(dloss_S)
            dlosses_.append(np.mean(dlosses__))
            glosses_.append(np.mean(glosses__))
            dlosses_Q_.append(np.mean(dlosses_Q__))
            dlosses_S_.append(np.mean(dlosses_S__))
            
        # print(len(agent.memory))
        # agent.start_learn()

        # if np.any(dones):                                   # exit loop if episode finished
        #     break
        if done:
            break

    #meanR = np.mean(Rs)
    #Rs_deque.append(meanR)
    Rs_deque.append(R)
    meanRs.append(np.mean(Rs_deque)) # plot
    
    dlosses.append(np.mean(dlosses_))
    glosses.append(np.mean(glosses_))
    dlosses_Q.append(np.mean(dlosses_Q_))
    dlosses_S.append(np.mean(dlosses_S_))

    print('\rEpisode {}\tTotal Average Score: {:.2f}\tGloss: {:.2f}\tDloss: {:.2f}\tDlossQ: {:.2f}\tDlossS: {:.2f}'.format(
            i_episode+1, np.mean(Rs_deque), np.mean(glosses_), np.mean(dlosses_), np.mean(dlosses_Q_), np.mean(dlosses_S_)))
    
    if np.mean(Rs_deque) >= R_goal:
        torch.save(agent.g.state_dict(), 'g-bipedal.pth')
        torch.save(agent.d.state_dict(), 'd-bipedal.pth')
        break

Episode 1	Total Average Score: -134.34	Gloss: -0.01	Dloss: 0.08	DlossQ: 0.00	DlossS: 0.08
Episode 2	Total Average Score: -119.48	Gloss: -0.04	Dloss: 7.94	DlossQ: 7.83	DlossS: 0.11
Episode 3	Total Average Score: -114.07	Gloss: -0.04	Dloss: 14.31	DlossQ: 14.18	DlossS: 0.12
Episode 4	Total Average Score: -124.72	Gloss: -0.04	Dloss: 18.09	DlossQ: 17.99	DlossS: 0.10
Episode 5	Total Average Score: -132.80	Gloss: -0.05	Dloss: 15.63	DlossQ: 15.57	DlossS: 0.06
Episode 6	Total Average Score: -130.25	Gloss: -0.05	Dloss: 10.85	DlossQ: 10.77	DlossS: 0.08
Episode 7	Total Average Score: -128.84	Gloss: -0.05	Dloss: 14.27	DlossQ: 14.19	DlossS: 0.08
Episode 8	Total Average Score: -127.49	Gloss: -0.05	Dloss: 14.26	DlossQ: 14.19	DlossS: 0.07
Episode 9	Total Average Score: -123.34	Gloss: -0.05	Dloss: 19.45	DlossQ: 19.38	DlossS: 0.07
Episode 10	Total Average Score: -123.34	Gloss: -0.05	Dloss: 19.97	DlossQ: 19.90	DlossS: 0.08
Episode 11	Total Average Score: -122.11	Gloss: -0.05	Dloss: 20.63	DlossQ: 20.55	Dlo

### 5. Plot the result

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(1,1,1)

plt.plot(np.arange(1, len(meanRs)+1), meanRs)
plt.ylabel('total_average_scores')
plt.xlabel('Episode #')
plt.show()

### 6. Watch the agent running with saved weights

In [36]:
# Load the saved weights into Pytorch model
agent.g.load_state_dict(torch.load('g-bipedal.pth', map_location='cpu'))
agent.d.load_state_dict(torch.load('d-bipedal.pth', map_location='cpu'))

# env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
# S = env_info.vector_observations                  # get the current states (S) (for each agent)
s = env.reset() # s: state # get the current state (s) (for an agent)
# print(s.shape)

#Rs = np.zeros(num_agents)                          # initialize the total scores (Rs) (for each agent)
R = 0 # R:total reward # initialize the total score (R) (for an agent)

while True:
    #A = agent.act(S)                        # select actions (A) from loaded model agents
    a = agent.act(np.reshape(s, [1, -1])) # a: [-1, +1]    # select action (a) from loaded model agent
    #a = agent.act(s)
    #print(s.shape, a.shape)
    
    # env_info = env.step(A)[brain_name]           # send all actions (A) to tne environment (env)
    # S2 = env_info.vector_observations         # get next states (S2) (for each agent)
    # rewards = env_info.rewards                         # get rewards (for each agent)
    # dones = env_info.local_done                        # see if the episode is done/finished (terminal)
    s2, r, done, _ = env.step(np.reshape(a, [-1]))
    #s2, r, done = env.step(a)
    
    # Rs += env_info.rewards                         # update the total scores (Rs) (for each agent)
    # S = S2                               # roll over current states (S) to next states (S2)
    R += r # update the total score (R) (for an agent)
    s = s2 # roll over current state (s) to next state (s2)
    
    #if np.any(dones):                                  # exit loop if episode is done/finished
    if done: # exit loop if episode is done/finished (terminal)
        break
        
print('Average of total scores: {}'.format(R))

Average of total scores: -106.75700939138544


When finished, you can close the environment.

In [37]:
env.close()