# Continuous Control

---

You are welcome to use this coding environment to train your agent for the project.  Follow the instructions below to get started!

### 1. Start the Environment

In [1]:
import gym
import random
import torch
import numpy as np
from collections import deque
import matplotlib.pyplot as plt
%matplotlib inline

Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [2]:
env = gym.make('BipedalWalker-v2')

random_seed = 10
env.seed(random_seed)

# from agent import Agent
# agent = Agent(state_size=env.observation_space.shape[0], action_size=env.action_space.shape[0], 
#               random_seed=random_seed)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


/home/arasdar/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


[10]

### 2. Examine the State and Action Spaces

Run the code cell below to print some information about the environment.

In [3]:
env.action_space, env.observation_space

(Box(4,), Box(24,))

In [4]:
action_size = env.action_space.shape[0]
state_size = env.observation_space.shape[0]

In [5]:
action_size, state_size

(4, 24)

In [6]:
env.observation_space.low, env.observation_space.high

(array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf], dtype=float32),
 array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       dtype=float32))

In [7]:
env.action_space.low, env.action_space.high

(array([-1., -1., -1., -1.], dtype=float32),
 array([1., 1., 1., 1.], dtype=float32))

### 3. Instantiate DDPG Agent

In [8]:
from agent import Agent

agent = Agent(s_size=state_size, a_size=action_size, random_seed=random_seed)

### 4. Train the Agent with DDPG

In [10]:
from collections import deque
import numpy as np
import time
import torch

n_episodes=1000
# n_steps=1000
# n_learn=10
# learn_every=20
R_goal=-90 # TOCHECK
Rs_deque = deque(maxlen=100)
meanRs = [] # plot
Rs = [] # plot

In [ ]:
for i_episode in range(n_episodes):
    
    # # Reset Env
    # env_info = env.reset(train_mode=train_mode)[brain_name]       # reset the environment    
    # S = env_info.vector_observations                   # get the current state (for each agent)
    s = env.reset() # s: state = [-inf, inf]
    s_ = np.zeros_like(s) # s_: predicted state = [-inf, inf]
    #print(s.shape)

    #Rs = np.zeros(num_agents)                            # initialize the score (for each agent)
    R = 0 # R: total reward

    #for i_step in range(n_steps):
    while True:
        s = np.reshape(s, [1, -1])
        s_ = np.reshape(s_, [1, -1])
        a = agent.act(s, s_) # a=[-1, 1]
        #a *= 2
        #print(a.shape)
        
        # Exploration noise
        # noise = np.random.normal(loc=0, scale=0.1, size=[num_agents, action_size])
        # A += noise
        # A = np.clip(a=A, a_min=-1, a_max=1)

        # env_info = env.step(A)[brain_name]            # send all actions to the environment
        # S2 = env_info.vector_observations          # get next state (for each agent)
        # rewards = env_info.rewards                          # get reward (for each agent)
        # dones = env_info.local_done                         # see if episode finished
        #s2: next_state, r: reward, done/terminal, env: environment
        #a = np.reshape(a, [-1])
        s2, r, done, _ = env.step(np.reshape(a, [-1]))
        #print(s2.shape, r, done)

        #s2_, q_ = agent.env(s, a)
        s2_, _ = agent.env(s, a)

        # for s, a, reward, s2, done in zip(S, A, rewards, S2, dones):
        # agent.step(state, action, reward, next_state, done) # send actions to the agent
        agent.step(s, a, r, s2, done, s_, s2_)

        R += r                           # update the score (for each agent)
        s = s2                                # roll over states to next time step
        s_ = s2_

        # if i_step%learn_every == 0:
        #     for _ in range(n_learn):
        #         agent.start_learn()
        #print(len(agent.memory))
        agent.start_learn()

        # if np.any(dones):                                   # exit loop if episode finished
        #     break
        if done:
            break

    #meanR = np.mean(Rs)
    #Rs_deque.append(meanR)
    Rs_deque.append(R)
    meanRs.append(np.mean(Rs_deque)) # plot
    Rs.append(R)

    print('\rEpisode {}\tTotal Average Score: {:.2f}'.format(i_episode+1, np.mean(Rs_deque)))  
    if np.mean(Rs_deque) >= R_goal:
        torch.save(agent.g.state_dict(), 'g-bipedal.pth')
        torch.save(agent.d.state_dict(), 'd-bipedal.pth')
        break

Episode 1	Total Average Score: -91.92
Episode 2	Total Average Score: -91.89
Episode 3	Total Average Score: -91.90
Episode 4	Total Average Score: -91.92
Episode 5	Total Average Score: -91.91
Episode 6	Total Average Score: -91.97
Episode 7	Total Average Score: -91.97
Episode 8	Total Average Score: -91.96
Episode 9	Total Average Score: -91.98
Episode 10	Total Average Score: -97.73
Episode 11	Total Average Score: -101.51
Episode 12	Total Average Score: -102.85
Episode 13	Total Average Score: -106.96
Episode 14	Total Average Score: -108.38
Episode 15	Total Average Score: -109.45
Episode 16	Total Average Score: -110.79
Episode 17	Total Average Score: -110.69
Episode 18	Total Average Score: -110.51
Episode 19	Total Average Score: -110.36
Episode 20	Total Average Score: -110.64
Episode 21	Total Average Score: -110.75
Episode 22	Total Average Score: -117.48
Episode 23	Total Average Score: -118.07
Episode 24	Total Average Score: -117.99
Episode 25	Total Average Score: -118.14
Episode 26	Total Av

Episode 204	Total Average Score: -108.87
Episode 205	Total Average Score: -108.93
Episode 206	Total Average Score: -108.94
Episode 207	Total Average Score: -108.99
Episode 208	Total Average Score: -109.18
Episode 209	Total Average Score: -109.38
Episode 210	Total Average Score: -109.44
Episode 211	Total Average Score: -109.43
Episode 212	Total Average Score: -109.51
Episode 213	Total Average Score: -109.49
Episode 214	Total Average Score: -109.58
Episode 215	Total Average Score: -109.65
Episode 216	Total Average Score: -109.66
Episode 217	Total Average Score: -109.70
Episode 218	Total Average Score: -109.67
Episode 219	Total Average Score: -109.70
Episode 220	Total Average Score: -109.71
Episode 221	Total Average Score: -109.66
Episode 222	Total Average Score: -109.97
Episode 223	Total Average Score: -109.94
Episode 224	Total Average Score: -110.19
Episode 225	Total Average Score: -110.36
Episode 226	Total Average Score: -110.35
Episode 227	Total Average Score: -111.51
Episode 228	Tota

Episode 404	Total Average Score: -128.26
Episode 405	Total Average Score: -128.22
Episode 406	Total Average Score: -127.78
Episode 407	Total Average Score: -127.12
Episode 408	Total Average Score: -127.13
Episode 409	Total Average Score: -126.50
Episode 410	Total Average Score: -125.86
Episode 411	Total Average Score: -125.79
Episode 412	Total Average Score: -125.66
Episode 413	Total Average Score: -125.15
Episode 414	Total Average Score: -124.93
Episode 415	Total Average Score: -125.43
Episode 416	Total Average Score: -125.62
Episode 417	Total Average Score: -125.71
Episode 418	Total Average Score: -125.78
Episode 419	Total Average Score: -126.30
Episode 420	Total Average Score: -125.99
Episode 421	Total Average Score: -126.76
Episode 422	Total Average Score: -126.85
Episode 423	Total Average Score: -126.98
Episode 424	Total Average Score: -126.86
Episode 425	Total Average Score: -126.59
Episode 426	Total Average Score: -126.79
Episode 427	Total Average Score: -126.90
Episode 428	Tota

### 5. Plot the result

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(1,1,1)

plt.plot(np.arange(1, len(meanRs)+1), meanRs)
plt.ylabel('total_average_scores')
plt.xlabel('Episode #')
plt.show()

### 6. Watch the agent running with saved weights

In [36]:
# Load the saved weights into Pytorch model
agent.g.load_state_dict(torch.load('g-bipedal.pth', map_location='cpu'))
agent.d.load_state_dict(torch.load('d-bipedal.pth', map_location='cpu'))

# env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
# S = env_info.vector_observations                  # get the current states (S) (for each agent)
s = env.reset() # s: state # get the current state (s) (for an agent)
s_ = np.zeros_like(s)# s_: predicted state # predict the current state (s) (by the agent)
# print(s.shape)

#Rs = np.zeros(num_agents)                          # initialize the total scores (Rs) (for each agent)
R = 0 # R:total reward # initialize the total score (R) (for an agent)

while True:
    #A = agent.act(S)                        # select actions (A) from loaded model agents
    s = np.reshape(s, [1, -1])
    s_ = np.reshape(s_, [1, -1])
    a = agent.act(s, s_) # a: [-1, +1]    # select action (a) from loaded model agent
    #a = agent.act(s)
    #print(s.shape, a.shape)
    
    # env_info = env.step(A)[brain_name]           # send all actions (A) to tne environment (env)
    # S2 = env_info.vector_observations         # get next states (S2) (for each agent)
    # rewards = env_info.rewards                         # get rewards (for each agent)
    # dones = env_info.local_done                        # see if the episode is done/finished (terminal)
    s2, r, done, _ = env.step(np.reshape(a, [-1]))
    #s2, r, done = env.step(a)
    
    #s2_, q_ = agent.env(s, a)
    s2_, _ = agent.env(s, a)
    
    # Rs += env_info.rewards                         # update the total scores (Rs) (for each agent)
    # S = S2                               # roll over current states (S) to next states (S2)
    R += r # update the total score (R) (for an agent)
    s = s2 # roll over current state (s) to next state (s2)
    s_ = s2_ # roll over the predcited current state (s) to the predicted next state (s2_)
    
    #if np.any(dones):                                  # exit loop if episode is done/finished
    if done: # exit loop if episode is done/finished (terminal)
        break
        
print('Average of total scores: {}'.format(R))

Average of total scores: -106.75700939138544


When finished, you can close the environment.

In [37]:
env.close()